name: Changelog CI

on:
  pull_request:
    types: [ opened ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run Changelog CI
        run: |
          echo 'Hello world!' >> hello.txt
          git config --global user.email "${GH_USERNAME}@users.noreply.github.com"
          git config --global user.name "${GH_USERNAME}"
          git add -A
          git commit -m "Fix version"
          git push
        env:
          GH_USERNAME: ${{ github.actor }}
